#!/bin/bash

python3 3d-odrpp.py instances/problema0.data | tee "saida_BFL_problema0.txt"
echo "Instância 0 completa"
python3 3d-odrpp.py instances/problema1.data | tee "saida_BFL_problema1.txt"
echo "Instância 1 completa"
python3 3d-odrpp.py instances/problema2.data | tee "saida_BFL_problema2.txt"
echo "Instância 2 completa"
python3 3d-odrpp.py instances/problema3.data | tee "saida_BFL_problema3.txt"
echo "Instância 3 completa"
python3 3d-odrpp.py instances/problema4.data | tee "saida_BFL_problema4.txt"
echo "Instância 4 completa"
python3 3d-odrpp.py instances/problema5.data | tee "saida_BFL_problema5.txt"
echo "Instância 5 completa"
python3 3d-odrpp.py instances/problema6.data | tee "saida_BFL_problema6.txt"
echo "Instância 6 completa"
python3 3d-odrpp.py instances/problema7.data | tee "saida_BFL_problema7.txt"
echo "Instância 7 completa"
python3 3d-odrpp.py instances/problema8.data | tee "saida_BFL_problema8.txt"
echo "Instância 8 completa"
python3 3d-odrpp.py instances/problema9.data | tee "saida_BFL_problema9.txt"
echo "Instância 9 completa"
python3 3d-odrpp.py instances/problema10.data | tee "saida_BFL_problema10.txt"
echo "Instância 10 completa"


python3 model.py instances/problema0.data | tee "saida_model_problema0.txt"
echo "Instância 0 completa"
python3 model.py instances/problema1.data | tee "saida_model_problema1.txt"
echo "Instância 1 completa"
python3 model.py instances/problema2.data | tee "saida_model_problema2.txt"
echo "Instância 2 completa"
python3 model.py instances/problema3.data | tee "saida_model_problema3.txt"
echo "Instância 3 completa"
python3 model.py instances/problema4.data | tee "saida_model_problema4.txt"
echo "Instância 4 completa"
python3 model.py instances/problema5.data | tee "saida_model_problema5.txt"
echo "Instância 5 completa"
python3 model.py instances/problema6.data | tee "saida_model_problema6.txt"
echo "Instância 6 completa"
python3 model.py instances/problema7.data | tee "saida_model_problema7.txt"
echo "Instância 7 completa"
python3 model.py instances/problema8.data | tee "saida_model_problema8.txt"
echo "Instância 8 completa"
python3 model.py instances/problema9.data | tee "saida_model_problema9.txt"
echo "Instância 9 completa"
python3 model.py instances/problema10.data | tee "saida_model_problema10.txt"
echo "Instância 10 completa"

